/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.controlador;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Usuarios;
import modelo.categoria;
import modelo.conexion;
import modelo.pregunta;

/**
 *
 * @author mateo
 */
public class vista_2 extends javax.swing.JFrame {

    int puntaje =0;
    conexion coneDB= new conexion();
    controlador controlador;
    LinkedList<categoria> c=new LinkedList<>();
    LinkedList<pregunta> a=new LinkedList<>();
     
    /**
     * Creates new form vista_2
     */
    public vista_2() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtnivel = new javax.swing.JTextField();
        txtcategoria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtpuntos = new javax.swing.JTextField();
        usuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtpregunta = new javax.swing.JLabel();
        rta1 = new javax.swing.JRadioButton();
        rta2 = new javax.swing.JRadioButton();
        rta3 = new javax.swing.JRadioButton();
        rta4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("Trivia");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel3.setText("Categoria:");

        jLabel1.setText("nivel:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtnivel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel4.setText("usuario:");

        jLabel5.setText("Puntaje:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(8, 8, 8)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtpuntos)
                    .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtpregunta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtpregunta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rta1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rta1ActionPerformed(evt);
            }
        });

        rta2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rta2ActionPerformed(evt);
            }
        });

        rta3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rta3ActionPerformed(evt);
            }
        });

        rta4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rta4ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Siguiente");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Salir");
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(77, 77, 77)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rta1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                    .addComponent(rta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30))))
                            .addComponent(txtpregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(txtpregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rta1))
                .addGap(18, 18, 18)
                .addComponent(rta2)
                .addGap(18, 18, 18)
                .addComponent(rta3)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rta4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rta1ActionPerformed
         rta2.setSelected(false);
         rta3.setSelected(false);
         rta4.setSelected(false);
    }//GEN-LAST:event_rta1ActionPerformed

    private void rta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rta2ActionPerformed
       rta1.setSelected(false);
       rta3.setSelected(false);
       rta4.setSelected(false);
    }//GEN-LAST:event_rta2ActionPerformed

    private void rta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rta3ActionPerformed
        rta1.setSelected(false);
        rta2.setSelected(false);
        rta4.setSelected(false);
    }//GEN-LAST:event_rta3ActionPerformed

    private void rta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rta4ActionPerformed
        rta1.setSelected(false);
        rta2.setSelected(false);
        rta3.setSelected(false);
    }//GEN-LAST:event_rta4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String rta = null;
        int nivelsumar=Integer.parseInt(txtnivel.getText());
        if(rta1.isSelected())
        {
            rta = rta1.getText();  
        }else 
            if(rta2.isSelected())
            {
               rta = rta2.getText();
            }else 
                if(rta3.isSelected())
                {
                   rta = rta3.getText();
                }else 
                     if(rta4.isSelected())
                     {
                        rta = rta4.getText();
                     }
        for (pregunta p : a) {
            
            if(rta == null)
            {
                verificarvacios();
            }else
                if(p.getRespuestacorrecta().equals(rta)){
                    JOptionPane.showMessageDialog(this, "respuesta correcta");
                    validar_puntaje();
                    txtpuntos.setText(String.valueOf(puntaje));
                    nivelsumar ++;
                    txtnivel.setText(String.valueOf(nivelsumar));
                    preguntas();
                    deseleccionar();
                    validar_final();
                }else{
                    validar2();
                    JOptionPane.showMessageDialog(this, "respuesta incorrecta,la respuesta correcta es" + p.getRespuestacorrecta());
                    dispose();
                    String nombres=usuario.getText();
                     perdio CrUsu = new perdio();
                     CrUsu.Mostrar(nombres,puntaje);
                     CrUsu.setVisible(true);
                }
             
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Connection cone=DriverManager.getConnection(coneDB.getUrl(), coneDB.getUser(), coneDB.getPassword());
            txtid.setVisible(false);
            preguntas();
        } catch (SQLException ex) 
        {
            Logger.getLogger(vista_principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void Mostrar(String Usuario,String nivel,String categoria)
    /*metodo para mostrar los datos respectivos de la persona que esta jugando*/
    {
        String puntajes=String.valueOf(puntaje);
        usuario.setText(Usuario);
        usuario.setEnabled(false);
        txtpuntos.setText(puntajes);
        txtpuntos.setEnabled(false);
        txtcategoria.setText(categoria);
        txtcategoria.setEnabled(false);
        txtnivel.setText(nivel);
        txtnivel.setEnabled(false);
    }
    
    public void preguntas()
    /*metodo para mostrar la preguntas en el formulario*/
    {
    String categorias= txtcategoria.getText();
    int nivel= Integer.parseInt(txtnivel.getText());
    this.controlador=new controlador();
    this.c=controlador.sacarcodigo(categorias);
    for (categoria categorias1 : c) 
        {
             String plan = String.valueOf(categorias1.getId());
             this.txtid.setText(plan);
        }
    int codigo= Integer.parseInt(txtid.getText());
    this.a=controlador.buscarpreguntas(codigo, nivel);
    for (pregunta p : a) {
             String pregunta = String.valueOf(p.getPregunta());
             String rta1 = String.valueOf(p.getRespuesta1());
             String rta2 = String.valueOf(p.getRespuesta2());
             String rta3 = String.valueOf(p.getRespuesta3());
             String rta4 = String.valueOf(p.getRespuestacorrecta());
             this.txtpregunta.setText(" " + pregunta);
             this.rta1.setText(rta1);
             this.rta2.setText(rta2);
             this.rta3.setText(rta3);
             this.rta4.setText(rta4);
             
        }
    }
    
    void deseleccionar()
    /*metodo para limpiar los radiobuttons al pasar a la siguiente pregunta*/
    {
    rta1.setSelected(false);
    rta2.setSelected(false);
    rta3.setSelected(false);
    rta4.setSelected(false);
    
    }
    
    public void verificarvacios()
    /*metodo para verificar que se tenga que escoger una respuesta*/
    {
       if((rta1.isSelected()==false&& rta2.isSelected()==false&& rta3.isSelected()==false&& rta4.isSelected()==false))
       {
          JOptionPane.showMessageDialog(this, "escoja 1 respuesta");
       } 
    }
   
    void validar_final()
    /*metodo para verificar que el juego acabo*/
    {
        int nivel=Integer.parseInt(txtnivel.getText());
        if(nivel>= 6) 
        {
            String nombre = usuario.getText();
            String puntaje = txtpuntos.getText();
            String categoria = txtcategoria.getText();
            Usuarios user = new Usuarios(nombre, puntaje,categoria);
            controlador controlador= new controlador();
            controlador.crearregistro(user);
            dispose();
            ganador CrUsu = new ganador();
            CrUsu.setVisible(true);
        }
    }
    void validar2()
    /*metodo para verificar cuando una persona perdio y se le deben guardar 
    los registros */
    {
        
        String nombre = usuario.getText();
        String puntaje = txtpuntos.getText();
        String categoria = txtcategoria.getText();
        Usuarios user = new Usuarios(nombre, puntaje,categoria);
        controlador controlador= new controlador();
        controlador.crearregistro2(user);
        
    }
    void validar_puntaje(){
        int nivel= Integer.parseInt(txtnivel.getText());
        switch (nivel)
        {
            case 1:
                puntaje=puntaje+100;
                break;
            case 2:
                puntaje=puntaje+200;
                break;
            case 3:
                puntaje=puntaje+300;
                break;
                 case 4:
                puntaje=puntaje+400;
                break;
                 case 5:
                puntaje=puntaje+500;
                break;
            default:
                break;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rta1;
    private javax.swing.JRadioButton rta2;
    private javax.swing.JRadioButton rta3;
    private javax.swing.JRadioButton rta4;
    private javax.swing.JTextField txtcategoria;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnivel;
    private javax.swing.JLabel txtpregunta;
    private javax.swing.JTextField txtpuntos;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
